### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toHtml' of undefined

### ISSUE THREAD

**Issue by hopewise** [Seicun/atom-watcher#1]
[Enter steps to reproduce below:]
1. install the package
2. create watcherConfig.js
3. save watcherConfig.js

**Atom Version**: 1.7.3
**System**: Microsoft Windows 10 Enterprise
**Thrown From**: [atom-watcher](https://github.com/Seicun/atom-watcher) package, v1.1.5
### Stack Trace

Uncaught TypeError: Cannot read property 'toHtml' of undefined

```
At C:\Users\Samir Sabri\.atom\packages\atom-watcher\lib\atom-watcher.js:173

TypeError: Cannot read property 'toHtml' of undefined
    at Socket.<anonymous> (C:\Users\Samir Sabri\.atom\packages\atom-watcher\lib\atom-watcher.js:173:58)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at Pipe.onread (net.js:523:20)
```
### Commands

```
     -8:22.1.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -8:21.3.0 core:select-all (atom-text-editor.editor.power-mode.is-focused)
     -8:20.9.0 core:delete (atom-text-editor.editor.power-mode.is-focused)
     -8:10.7.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -7:40.5.0 core:select-all (atom-text-editor.editor.power-mode.is-focused)
     -7:40.1.0 core:delete (atom-text-editor.editor.power-mode.is-focused)
     -6:25.2.0 core:select-all (atom-text-editor.editor.power-mode.is-focused)
     -6:24.7.0 core:delete (atom-text-editor.editor.power-mode.is-focused)
     -6:24.4.0 core:save (atom-text-editor.editor.power-mode.is-focused)
     -1:05.8.0 core:move-left (atom-text-editor.editor.mini.is-focused)
     -0:21 atom-watcher:toggle (atom-text-editor.editor.power-mode.is-focused)
     -0:09.7.0 tree-view:add-file (span.name.icon.icon-file-directory)
     -0:09.0 core:paste (atom-text-editor.editor.mini.is-focused)
     -0:08.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:03.8.0 atom-watcher:toggle (atom-text-editor.editor.is-focused.power-mode)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "atom-elixir",
      "build-elixir",
      "terminal-plus",
      "autocomplete-haxe",
      "haxe",
      "haxe-import",
      "haxe-newfile",
      "language-haxe"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.5.2
atom-watcher, v1.1.5
autocomplete-elixir, v1.5.13
elixir-cmd, v0.2.9
language-elixir, v0.12.3
linter, v1.11.4
linter-xo, v0.15.0
phoenix-snippets, v0.5.0
platformio-ide-terminal, v2.0.9

# Dev
No dev packages
```

**Comment by maevic** [comment]
Hi, sorry for my late response.

Unfortunately I cannot reproduce this error. I tried it on Linux and Windows 8. Does this error happens to you every time or just occasionally?

**Comment by maevic** [comment]
I close this one due to lack of response. Please feel free to reopen.
